2022/9/3 14:38:28:捕获未处理异常:DialogHost is already open.
2022/9/3 15:47:31:捕获未处理异常:DialogHost is already open.
2022/9/3 15:47:38:捕获未处理异常:调用的目标发生了异常。
2022/9/3 15:47:43:捕获线程内未处理异常：未通过等待任务或访问任务的 Exception 属性观察到任务的异常。因此，终结器线程重新引发了未观察到的异常。
2022/9/3 16:37:04:捕获未处理异常:DialogHost is already open.
2022/9/3 16:37:13:捕获未处理异常:调用的目标发生了异常。
2022/9/3 16:37:15:捕获线程内未处理异常：未通过等待任务或访问任务的 Exception 属性观察到任务的异常。因此，终结器线程重新引发了未观察到的异常。
2022/9/3 20:23:25:捕获未处理异常:DialogHost is already open.
2022/9/3 20:24:02:捕获未处理异常:调用的目标发生了异常。
2022/9/3 20:37:10:捕获未处理异常:DialogHost is already open.
2022/9/3 20:37:10:捕获线程内未处理异常：未通过等待任务或访问任务的 Exception 属性观察到任务的异常。因此，终结器线程重新引发了未观察到的异常。
2022/9/3 20:53:14:捕获线程内未处理异常：未通过等待任务或访问任务的 Exception 属性观察到任务的异常。因此，终结器线程重新引发了未观察到的异常。
2022/9/3 21:38:41:捕获线程内未处理异常：未通过等待任务或访问任务的 Exception 属性观察到任务的异常。因此，终结器线程重新引发了未观察到的异常。
